import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";

// Server-side metadata uses direct env access (no NEXT_PUBLIC_ prefix needed
// here — this module never ships to the browser bundle). Falls back to the
// same defaults as the client config module.
const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME ?? "PlumbTrack";
const ORG_NAME = process.env.NEXT_PUBLIC_ORG_NAME ?? "Caulfield South Plumbing";

// Slack uses Lato — self-hosted via next/font so the typography stays authentic
// without render-blocking external font requests.
const lato = Lato({
  weight: ["400", "700", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: `${APP_NAME} — ${ORG_NAME}`,
  description: "Field service quoting, job tracking and invoicing for plumbers.",
  // PWA installability — manifest (apps/web/src/app/manifest.ts) plus icons
  // generated by `pnpm icons:gen`. `display: standalone` + appleWebApp make
  // the installed app open full-screen with no browser chrome.
  manifest: "/manifest.webmanifest",
  icons: {
    icon: [
      { url: "/favicon.png", sizes: "32x32", type: "image/png" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  appleWebApp: {
    title: APP_NAME,
    // Content underlaps the status bar (viewport-fit: cover) — the app
    // header's safe-area-inset-top padding keeps it clear of the notch.
    statusBarStyle: "black-translucent",
  },
  other: {
    // Legacy standalone-mode signal. (Next 15.x maps appleWebApp.capable to
    // the wrong tag and auto-emits mobile-web-app-capable itself, so only the
    // Apple tag needs declaring here.)
    "apple-mobile-web-app-capable": "yes",
  },
};

export function generateViewport() {
  return {
    themeColor: "#071022",
    width: "device-width",
    initialScale: 1,
    viewportFit: "cover",
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${lato.variable} ${process.env.NODE_ENV === "development" ? "dev" : ""}`}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
