import type { MetadataRoute } from "next";

const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME ?? "PlumbTrack";
const ORG_NAME = process.env.NEXT_PUBLIC_ORG_NAME ?? "Caulfield South Plumbing";

/** Served at /manifest.webmanifest — makes PlumbTrack installable to the
 *  home screen as a standalone, full-screen app (Chrome/Android + Edge).
 *  Icons are generated by `pnpm icons:gen` (scripts/gen-icons.mjs). */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${APP_NAME} — ${ORG_NAME}`,
    short_name: APP_NAME,
    description: "Field service quoting, job tracking and invoicing for plumbers.",
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    lang: "en-AU",
    categories: ["business", "productivity"],
    background_color: "#071022",
    theme_color: "#071022",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icon-512-maskable.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
